### ISSUE TITLE
you should have a sha256 sum to verify what a user is getting

### ISSUE THREAD

**Issue by kbroughton** [philipperemy/tensorflow-1.4-billion-password-analysis#2]
it would be nice to have a sha256 sum for validation

**Comment by philipperemy** [comment]
Agreed but it's not the compressed version so might be hard to provide a checksum for validation.

**Comment by philipperemy** [comment]
Done in https://github.com/philipperemy/tensorflow-1.4-billion-password-analysis/commit/3343affabaf94698d92b4285cafcc1c9fed8767f
