### ISSUE TITLE
password separator

### ISSUE THREAD

**Issue by denemmy** [philipperemy/tensorflow-1.4-billion-password-analysis#5]
https://github.com/philipperemy/tensorflow-1.4-billion-password-analysis/blob/c5f0c4899bba8fd30f415ccc19d079ff412056ca/utils.py#L12

I think there are also lines where ';' is used as separator instead of ':'

**Comment by philipperemy** [comment]
@denemmy thanks I'm going to add that. I have time to push new stuffs and features now :)

**Comment by philipperemy** [comment]
Fixed in https://github.com/philipperemy/tensorflow-1.4-billion-password-analysis/commit/d3a4cdedb1ac23c24c1b28551fa9b92b8c587463
