### ISSUE TITLE
List Disk Space Required

### ISSUE THREAD

**Issue by m56789** [philipperemy/tensorflow-1.4-billion-password-analysis#6]
You need to note the amount of disk space required to have read.py run. Seems like maybe 50GB? I keep filling up VMs. 

Also defaulting to ~/ for temp space is fine on a desktop with a large HDD, but not ideal on a cloud provider that has like a 60GB boot disk. If I have time I will do a pull request with some updates to select where temp work is performed. 

Thank you for sharing your work.

**Comment by m56789** [comment]
Thanks for sharing

**Comment by philipperemy** [comment]
Done!

Thanks for your useful comment :)

https://github.com/philipperemy/tensorflow-1.4-billion-password-analysis#data-explanation
